# Generated by Django 4.1 on 2022-08-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagementsystem',
            name='city',
        ),
    ]
