# Generated by Django 4.1 on 2022-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_remove_usermanagementsystem_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagementsystem',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
